### ISSUE TITLE
Buy/sell Shops Infinite Money Bug

### ISSUE THREAD

**Issue by galoti** [rm2023/Dynamic-Shops#2]
Hello rm2023! I think Buy/Sell shops have a problem. In this example - /ds createShop GlowstoneEmporium 1 10 0.05 - I can buy for 5.5 dollars and then sell for 6.31

**Comment by Robit** [comment]
Hmm, that's a design error I should have anticipated. Thanks for letting me know. I think a good solution would be modifying the sell price so the sell price the price of the next item to be bought and the buy price is the price of the next item to be sold.
