### ISSUE TITLE
Delete Signs

### ISSUE THREAD

**Issue by luke198** [rm2023/Dynamic-Shops#5]
How do I delete a sign? I tried Worldedit and punching it, and nothing is working.

**Comment by Robit** [comment]
You're able to delete a sign if you break it by hand while having the dynamicshops.admin permission (or op). Please let me know if that isn't working and see if a debug level message is appearing in the logs when you try to do it.

**Comment by Robit** [comment]
Oh, I wrote the permission check wrong. Op should still work, though. I'll quickly make a release that checks for permissions correctly. Thanks for making a report!
