### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Lordioz** [rm2023/Dynamic-Shops#7]
so when I launch the plugin for the first time everything goes well but when I restart my server the plugin no longer works

**Comment by Robit** [comment]
Hmm, could you attach your server logs for when the plugin fails to work as well as the shops_db file located in the Dynamic Shops folder in the config directory?

**Comment by Lordioz** [comment]
Well the weird thing is that there is nothing ... the plugin simply stops
working when I create shops or delete shops alone.

**Comment by Robit** [comment]
So the commands stop responding? I feel like that means your shops_db might not be loading correctly but I can't know for sure unless you upload that and your logs from when the plugin stops working. The relevant files should be /config/dynamicshops/shops_db and /logs/latest.log

**Comment by Lordioz** [comment]
correct the store will delete the shops on its own and even more
incredible, no message, maybe a bug with another shop?

**Comment by Robit** [comment]
Do you have access to the log and database files that I'm requesting?

**Comment by Lordioz** [comment]
yes obviously but it's a bit of a mess, good luck

**Comment by Lordioz** [comment]
here

Le jeu. 23 janv. 2020 à 19:37, Vyts Pénard <maximeravyts32@gmail.com> a
écrit :

> yes obviously but it's a bit of a mess, good luck
>

**Comment by Lordioz** [comment]
if you need more tell me

Le jeu. 23 janv. 2020 à 19:37, Vyts Pénard <maximeravyts32@gmail.com> a
écrit :

**Comment by Robit** [comment]
Could you upload them via github rather than through an email? If you're attaching them to the email you sent, they aren't being sent to github. You need to view the issue on github and drag and drop the files into a new reply

**Comment by Robit** [comment]
Closed due to lack of logs. If you're able to upload the requested files or put them on pastebin/google drive and link them here, I'll be able to reopen the issue and investigate it
